# Transform a cloud to an collisonObject

# (Optional) list shapes to try e.g. "sphere cylinder box"
string[] shapes
# (Optional) table
shape_msgs/Plane table_plane
bool use_plane

sensor_msgs/PointCloud2 source_cloud
---
moveit_msgs/CollisionObject collision_object